version: 2.1
orbs:
  slack: circleci/slack@4.12.5
  
jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      
      - run:
          name: install npm
          command: npm install
      - run:
          name: run unit tests
          command: npm test
      - run:
          name: generate code coverage report
          command: npm run coverage
          
      - store_test_results:
          path: .circleci/test-results
      - store_artifacts:
          path: .circleci/coverage
          
workflows:
  version: 2.1
  build-and-store-artifacts:
    jobs:
      - build

      - slack/notify:
          channel: general
          event: fail
          template: basic_fail_1
          mentions: 
            - username: "<@your_slack_username>"
          content: "This is Milton Francom submitting the Slack assignment"
