version: 2.1

jobs:
  build:
    orbs:
      node: circleci/node@5.1.0

    steps:
      - checkout
      
      - run:
          name: install npm
          command: npm install
      - run:
          name: run unit tests
          command: npm test --coverage
      - run:
          name: generate code coverage report
          command: npm run coverage
 # workflows:
  #build-and-store-artifacts:
   # jobs:
    #  - build
     # - store_artifacts:
      #    path: test-results
      #- store_artifacts:
      #    path: coverage
